site_name: Gabriel Santos
site_url: https://gabriels999.github.io/mkdocs-resumes/
nav:
    - Home: index.md
    - Brag Document: brag.md
    - Pessoais: about.md
    - Profissionais: skills.md

theme:
  favicon: img/favicon.ico
  name: material
  palette:
    - scheme: slate
      primary: deep blue
      toggle:
        icon: material/weather-night
        name: dark
    - scheme: default
      primary: yellow
      toggle:
        icon: material/weather-sunny
        name: day
  features:
    - navigation.tabs

extra_css:
  - stylesheets/extra/css